// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: api/v1/mall.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	MaxPrice string `protobuf:"bytes,2,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"`
	MinPrice string `protobuf:"bytes,3,opt,name=minPrice,proto3" json:"minPrice,omitempty"`
}

func (x *LGRequest) Reset() {
	*x = LGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_mall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LGRequest) ProtoMessage() {}

func (x *LGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LGRequest.ProtoReflect.Descriptor instead.
func (*LGRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_mall_proto_rawDescGZIP(), []int{0}
}

func (x *LGRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LGRequest) GetMaxPrice() string {
	if x != nil {
		return x.MaxPrice
	}
	return ""
}

func (x *LGRequest) GetMinPrice() string {
	if x != nil {
		return x.MinPrice
	}
	return ""
}

type LGResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods []*Goods `protobuf:"bytes,3,rep,name=goods,proto3" json:"goods,omitempty"`
}

func (x *LGResponse) Reset() {
	*x = LGResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_mall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LGResponse) ProtoMessage() {}

func (x *LGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LGResponse.ProtoReflect.Descriptor instead.
func (*LGResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_mall_proto_rawDescGZIP(), []int{1}
}

func (x *LGResponse) GetGoods() []*Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

type Goods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Count string `protobuf:"bytes,3,opt,name=count,proto3" json:"count,omitempty"`
	Id    string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Goods) Reset() {
	*x = Goods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_mall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_api_v1_mall_proto_rawDescGZIP(), []int{2}
}

func (x *Goods) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goods) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Goods) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

func (x *Goods) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_v1_mall_proto protoreflect.FileDescriptor

var file_api_v1_mall_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0x57, 0x0a, 0x09, 0x4c, 0x47, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x22, 0x2d, 0x0a, 0x0a, 0x4c, 0x47, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x22,
	0x57, 0x0a, 0x05, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x34, 0x0a, 0x04, 0x4d, 0x61, 0x6c, 0x6c,
	0x12, 0x2c, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x0d, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x47, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07,
	0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_mall_proto_rawDescOnce sync.Once
	file_api_v1_mall_proto_rawDescData = file_api_v1_mall_proto_rawDesc
)

func file_api_v1_mall_proto_rawDescGZIP() []byte {
	file_api_v1_mall_proto_rawDescOnce.Do(func() {
		file_api_v1_mall_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_mall_proto_rawDescData)
	})
	return file_api_v1_mall_proto_rawDescData
}

var file_api_v1_mall_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_mall_proto_goTypes = []interface{}{
	(*LGRequest)(nil),  // 0: v1.LGRequest
	(*LGResponse)(nil), // 1: v1.LGResponse
	(*Goods)(nil),      // 2: v1.Goods
}
var file_api_v1_mall_proto_depIdxs = []int32{
	2, // 0: v1.LGResponse.goods:type_name -> v1.Goods
	0, // 1: v1.Mall.ListGoods:input_type -> v1.LGRequest
	1, // 2: v1.Mall.ListGoods:output_type -> v1.LGResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_mall_proto_init() }
func file_api_v1_mall_proto_init() {
	if File_api_v1_mall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_mall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_mall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LGResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_mall_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Goods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_mall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_mall_proto_goTypes,
		DependencyIndexes: file_api_v1_mall_proto_depIdxs,
		MessageInfos:      file_api_v1_mall_proto_msgTypes,
	}.Build()
	File_api_v1_mall_proto = out.File
	file_api_v1_mall_proto_rawDesc = nil
	file_api_v1_mall_proto_goTypes = nil
	file_api_v1_mall_proto_depIdxs = nil
}
